### ISSUE TITLE
Ubuntu 22 fails to build

### ISSUE THREAD

**Issue by realsetvin** [realsetvin/vkax#6]
Autogen fails

autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1

guessing its a package issue

steps to reproduce on ubuntu 22

```
sudo apt update && sudo apt upgrade &&
git clone https://github.com/realsetvin/vkax/ &&
cd vkax/depends/ &&
chmod +x conf* &&
make &&
cd .. &&
./autogen.sh &&
./configure --disable-tests --disable-bench --enable-glibc-back-compat --prefix=$PWD/depends/x86_64-pc-linux-gnu/ &&
make
```

**Comment by DC4JG** [comment]
Looks like the error lines

```
/usr/bin/m4:configure.ac:1835: Warning: excess arguments to builtin `patsubst' ignored
/usr/bin/m4:configure.ac:1843: Warning: excess arguments to builtin `patsubst' ignored
```

refer to the following [lines in code](https://github.com/realsetvin/vkax/blob/fab1a333c100868d497e3928be9418aee613eb97/configure.ac#L1834)

```c
define(_COPYRIGHT_HOLDERS_FINAL, [patsubst(_COPYRIGHT_HOLDERS, [%s], [_COPYRIGHT_HOLDERS_SUBSTITUTION])])
AC_DEFINE(COPYRIGHT_HOLDERS_FINAL, "_COPYRIGHT_HOLDERS_FINAL", [Copyright holder(s)])
AC_SUBST(CLIENT_VERSION_MAJOR, _CLIENT_VERSION_MAJOR)
AC_SUBST(CLIENT_VERSION_MINOR, _CLIENT_VERSION_MINOR)
AC_SUBST(CLIENT_VERSION_BUILD, _CLIENT_VERSION_BUILD)
AC_SUBST(CLIENT_VERSION_IS_RELEASE, _CLIENT_VERSION_IS_RELEASE)
AC_SUBST(COPYRIGHT_YEAR, _COPYRIGHT_YEAR)
AC_SUBST(COPYRIGHT_HOLDERS, "_COPYRIGHT_HOLDERS")
AC_SUBST(COPYRIGHT_HOLDERS_SUBSTITUTION, "_COPYRIGHT_HOLDERS_SUBSTITUTION")
AC_SUBST(COPYRIGHT_HOLDERS_FINAL, "_COPYRIGHT_HOLDERS_FINAL")
```

According to this [thread on stackexchange](https://unix.stackexchange.com/questions/501134/expanding-a-macro-into-quotes-in-m4) it might be related to the way different flavors of Linux handle this case.

**Comment by realsetvin** [comment]
> Looks like the error lines
> 
> ```
> /usr/bin/m4:configure.ac:1835: Warning: excess arguments to builtin `patsubst' ignored
> /usr/bin/m4:configure.ac:1843: Warning: excess arguments to builtin `patsubst' ignored
> ```
> 
> refer to the following [lines in code](https://github.com/realsetvin/vkax/blob/fab1a333c100868d497e3928be9418aee613eb97/configure.ac#L1834)
> 
> ```c
> define(_COPYRIGHT_HOLDERS_FINAL, [patsubst(_COPYRIGHT_HOLDERS, [%s], [_COPYRIGHT_HOLDERS_SUBSTITUTION])])
> AC_DEFINE(COPYRIGHT_HOLDERS_FINAL, "_COPYRIGHT_HOLDERS_FINAL", [Copyright holder(s)])
> AC_SUBST(CLIENT_VERSION_MAJOR, _CLIENT_VERSION_MAJOR)
> AC_SUBST(CLIENT_VERSION_MINOR, _CLIENT_VERSION_MINOR)
> AC_SUBST(CLIENT_VERSION_BUILD, _CLIENT_VERSION_BUILD)
> AC_SUBST(CLIENT_VERSION_IS_RELEASE, _CLIENT_VERSION_IS_RELEASE)
> AC_SUBST(COPYRIGHT_YEAR, _COPYRIGHT_YEAR)
> AC_SUBST(COPYRIGHT_HOLDERS, "_COPYRIGHT_HOLDERS")
> AC_SUBST(COPYRIGHT_HOLDERS_SUBSTITUTION, "_COPYRIGHT_HOLDERS_SUBSTITUTION")
> AC_SUBST(COPYRIGHT_HOLDERS_FINAL, "_COPYRIGHT_HOLDERS_FINAL")
> ```
> 
> According to this [thread on stackexchange](https://unix.stackexchange.com/questions/501134/expanding-a-macro-into-quotes-in-m4) it might be related to the way different flavors of Linux handle this case.

Aha! You solved the issue!

I made this change 

![image](https://github.com/realsetvin/vkax/assets/117243445/60ecaf2d-191c-44da-9853-9b5df3d36909)

**Comment by realsetvin** [comment]
commit
004f1cb6ab9ef58f8b28599c9108b70f6f7f0b34

I will test this change to make sure it can build now

**Comment by realsetvin** [comment]
Looks like we can build successfully now! Thank you so much for your contribution!
